import DashboardLayout from "@/components/common/layout/DashboardLayout";
import Footer from "@/components/common/layout/footer";
import LanderNavbar1 from "@/components/common/layout/navbar/LanderNavbar1";
import NewsLetter from "@/components/lander/home/newsLetter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GG Subscription | Home",
  description: "Generated by create next app",
};

export default function Dashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-[#0D0D0D]">
      <LanderNavbar1 showOffer={false} />
      <DashboardLayout>{children}</DashboardLayout>
      <NewsLetter />
      <Footer />
    </main>
  );
}
