import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GG Subscription | Home",
  description: "Generated by create next app",
};

export default function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="bg-green-500">{children}</main>;
}
