import Footer from "@/components/common/layout/footer";
import LanderLayout from "@/components/common/layout/LanderLayout";
import NewsLetter from "@/components/lander/home/newsLetter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GG Subscription | Home",
  description: "Generated by create next app",
};

export default function Lander({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-[#161616]">
      <LanderLayout>{children}</LanderLayout>
      <NewsLetter />
      <Footer />
    </main>
  );
}
